=== Manuelvilpas/2324_lmsgi/ud4/prueba 1/02.dtd
<!ELEMENT continente (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT capital (#PCDATA)>
<!ELEMENT fila (continente, pais, capital)>
<!ELEMENT mundo (fila+)>
<!ATTLIST mundo xmlns:xsi CDATA #IMPLIED > 
<!ATTLIST mundo xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

=== Manuelvilpas/2324_lmsgi/ud4/prueba 1/02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mundo SYSTEM "02.dtd">

<mundo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="02.xsd">
    <fila>
        <continente>Europa</continente>
        <pais>Alemania</pais>
        <capital>berlín</capital>
    </fila>
    <fila>
        <continente>América</continente>
        <pais>Argentina</pais>
        <capital>Buenos Aires</capital>
    </fila>
    <fila>
        <continente>América</continente>
        <pais>Bahamas</pais>
        <capital>Nassau</capital>
    </fila>
    <fila>
        <continente>Asia</continente>
        <pais>Afganistán</pais>
        <capital>Kabul</capital>
    </fila>
    <fila>
        <continente>Asia</continente>
        <pais>Arabia Saudita</pais>
        <capital>Riad</capital>
    </fila>
</mundo>
