=== Manuelvilpas/2324_lmsgi/ud4/prueba 1/05.dtd
<!ELEMENT Companyia (empleado)>
    <!ELEMENT empleado (nombre,apellido,numero,gmail,direccion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT numero (#PCDATA)>
    <!ELEMENT gmail (#PCDATA)>
    <!ELEMENT direccion (ciudad,estado,zip)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT estado (#PCDATA)>
    <!ELEMENT zip (#PCDATA)>

    <!ATTLIST Companyia xmlns:xsi CDATA #IMPLIED>
    <!ATTLIST Companyia xsi:noNamespaceSchemaLocation CDATA #IMPLIED>

=== Manuelvilpas/2324_lmsgi/ud4/prueba 1/05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Companyia SYSTEM "05.dtd">
<Companyia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="05.xsd">
    <empleado>
        <nombre>Petrusco</nombre>
        <apellido>Java</apellido>
        <numero>123456789</numero>
        <gmail>Petruscodel15@gmail.com</gmail>
        <direccion>
            <ciudad>Ubuntu</ciudad>
            <estado>Karnataka</estado>
            <zip>560212</zip>
        </direccion>
    </empleado>
</Companyia>
