=== Manuelvilpas/2324_lmsgi/ud4/prueba 1/10.dtd
<!ELEMENT pagina (receta+)>
<!ELEMENT receta (nombre+,descripcion?,tiempo+,ingredientes+,instrucciones+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT tiempo EMPTY> <!-- numeros que van enre 1 y 999-->
        <!ATTLIST tiempo preparacion CDATA #REQUIRED>
        <!ATTLIST tiempo coccion ID #IMPLIED>
    <!ELEMENT ingredientes (ingrediente*)>
        <!ELEMENT ingrediente (nombrei, cantidad?)>
            <!ELEMENT nombrei (#PCDATA)>
            <!ELEMENT cantidad (#PCDATA)>
                <!ATTLIST cantidad unidad (gramos|pizca|mililitros|cuchadara|chorro) #IMPLIED>
    <!ELEMENT instrucciones (pasos+)>
        <!ELEMENT pasos (#PCDATA)>
    <!ATTLIST receta plato (primero|segundo|postre) "primero">

=== Manuelvilpas/2324_lmsgi/ud4/prueba 1/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pagina SYSTEM "10.dtd">
<pagina>
    <receta plato="primero">
        <nombre>Risoto Milanesa</nombre>
        <tiempo preparacion=""/>
        <ingredientes>
            <ingrediente>
                <nombrei>arroz</nombrei>
                <cantidad unidad="gramos">500</cantidad>
            </ingrediente>
            <ingrediente>
                <nombrei>cebolla mediana</nombrei>
                <cantidad>1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombrei>azafran</nombrei>
                <cantidad unidad="pizca">1</cantidad>
            </ingrediente>
            <ingrediente>
                <nombrei>queso parmesano</nombrei>
                <cantidad unidad="gramos">100</cantidad>
            </ingrediente>
            <ingrediente>
                <nombrei>mantequilla</nombrei>
                <cantidad unidad="gramos">100</cantidad>
            </ingrediente>
            <ingrediente>
                <nombrei>sal</nombrei>
            </ingrediente>
            <ingrediente>
                <nombrei>pimienta</nombrei>
            </ingrediente>
            <ingrediente>
                <nombrei>caldo</nombrei>
                <cantidad unidad="mililitros">1000</cantidad>
            </ingrediente>
            <ingrediente>
                <nombrei>vino blanc</nombrei>
                <cantidad unidad="chorro">1</cantidad>
            </ingrediente>
        </ingredientes>
        <instrucciones>
            <pasos>Picamos la cebolla y la pochamos con la mitad de la mantequilla.</pasos>
            <pasos>Cuando esté transparente, echamos el azafrán,el vino y dejamos que reduzca.</pasos>
            <pasos>A continuación, incorporamos el arroz, lo sofreímos un poco</pasos>
            <pasos>Vamos añadiendo el caldo caliente poco a poco mientras removemos.</pasos>
            <pasos>Salpimentamos</pasos>
            <pasos>Cuando esté casi hecho, agregamos el resto de la mantequilla y el queso.</pasos>
            <pasos>Servimos enseguida.</pasos>
        </instrucciones>
    </receta>
</pagina>
